---
title: "Plotting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE}
library(faux)
library(cowplot)
```


## One-factor designs

```{r, fig.width=7, fig.height=5}
p1 <- check_design(plot = FALSE) %>% plot_design()
p2 <- check_design(2, plot = FALSE) %>% plot_design()
p3 <- check_design(3, plot = FALSE) %>% plot_design()
p4 <- check_design(4, plot = FALSE) %>% plot_design()
p5 <- check_design(5, plot = FALSE) %>% plot_design()
p6 <- check_design(6, plot = FALSE) %>% plot_design()
p7 <- check_design(7, plot = FALSE) %>% plot_design()
p8 <- check_design(8, plot = FALSE) %>% plot_design()
p9 <- check_design(9, plot = FALSE) %>% plot_design()

cowplot::plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrow = 3)
```

## Two-factor designs

```{r, fig.width=10, fig.height=8}
p1 <- check_design(c(2,2), mu = 1:4, plot = FALSE) %>% plot_design()
p2 <- check_design(c(2,3), mu = 1:6, plot = FALSE) %>% plot_design()
p3 <- check_design(c(2,4), mu = 1:8, plot = FALSE) %>% plot_design()
p4 <- check_design(c(3,2), mu = 1:6, plot = FALSE) %>% plot_design()
p5 <- check_design(c(3,3), mu = 1:9, plot = FALSE) %>% plot_design()
p6 <- check_design(c(3,4), mu = 1:12, plot = FALSE) %>% plot_design()
p7 <- check_design(c(4,2), mu = 1:8, plot = FALSE) %>% plot_design()
p8 <- check_design(c(4,3), mu = 1:12, plot = FALSE) %>% plot_design()
p9 <- check_design(c(4,4), mu = 1:16, plot = FALSE) %>% plot_design()

cowplot::plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrow = 3)
```

## Three-factor designs

```{r, fig.width=15, fig.height=13}
p1 <- check_design(c(2,2,2), mu = 1:8, plot = FALSE) %>% plot_design()
p2 <- check_design(c(2,3,2), mu = 1:12, plot = FALSE) %>% plot_design()
p3 <- check_design(c(2,4,2), mu = 1:16, plot = FALSE) %>% plot_design()
p4 <- check_design(c(3,2,2), mu = 1:12, plot = FALSE) %>% plot_design()
p5 <- check_design(c(3,3,2), mu = 1:18, plot = FALSE) %>% plot_design()
p6 <- check_design(c(3,4,2), mu = 1:24, plot = FALSE) %>% plot_design()
p7 <- check_design(c(4,2,2), mu = 1:16, plot = FALSE) %>% plot_design()
p8 <- check_design(c(4,3,2), mu = 1:24, plot = FALSE) %>% plot_design()
p9 <- check_design(c(4,4,2), mu = 1:32, plot = FALSE) %>% plot_design()

cowplot::plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrow = 3)
```

## Four-factor designs

```{r, fig.width=20, fig.height=18}
p1 <- check_design(c(2,2,3,2), mu = 1:24, plot = FALSE) %>% plot_design()
p2 <- check_design(c(2,3,3,2), mu = 1:36, plot = FALSE) %>% plot_design()
p3 <- check_design(c(2,4,3,2), mu = 1:48, plot = FALSE) %>% plot_design()
p4 <- check_design(c(3,2,3,2), mu = 1:36, plot = FALSE) %>% plot_design()
p5 <- check_design(c(3,3,3,2), mu = 1:54, plot = FALSE) %>% plot_design()
p6 <- check_design(c(3,4,3,2), mu = 1:72, plot = FALSE) %>% plot_design()
p7 <- check_design(c(4,2,3,2), mu = 1:48, plot = FALSE) %>% plot_design()
p8 <- check_design(c(4,3,3,2), mu = 1:72, plot = FALSE) %>% plot_design()
p9 <- check_design(c(4,4,3,2), mu = 1:96, plot = FALSE) %>% plot_design()

cowplot::plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, p9, nrow = 3)
```

## Five-factor designs

```{r}
check_design(c(2,2,2,2,2), mu = 1:(2^5))
```

## Six-factor designs

```{r}
check_design(c(2,2,2,2,2,2), mu = 1:(2^6))
```