---
title: "multisim"
date: "19/10/2018"
output: html_document
---

```{r}
library(multisim)
```


## specify cors 

### a vars\*vars matrix

```{r}
cmat <- matrix(c(1, .3, .5,
                .3, 1, 0,
                .5, 0, 1), 3)
bvn <- multirnorm(100, 3, cmat, varnames = c("first", "second", "third"))
cor(bvn) # check correlation matrix
```

### a vars\*vars length vector

```{r}
cmat <- c(1, .3, .5,
          .3, 1, 0,
          .5, 0, 1)
bvn <- multirnorm(100, 3, cmat, varnames = c("first", "second", "third"))
cor(bvn) # check correlation matrix
```

### a single r for all pairs
```{r}
bvn <- multirnorm(100, 5, .3, varnames = letters[1:5])
cor(bvn) # check correlation matrix
```

### vars\*(vars-1)/2 length vector
```{r}
rho1_2 <- .3
rho1_3 <- .5
rho1_4 <- .5
rho2_3 <- .2
rho2_4 <- 0
rho3_4 <- -.3
cmat <- c(rho1_2, rho1_3, rho1_4, rho2_3, rho2_4, rho3_4)
bvn <- multirnorm(100, 4, cmat, varnames = letters[1:4])
cor(bvn) # check correlation matrix
```

## empirical
```{r}
bvn_exact <- multirnorm(100, 5, .3, varnames = letters[1:5], empirical = T)
cor(bvn_exact) # check correlation matrix
```

